//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiPhi
    {
        public string MaCongViecChiTieu { get; set; }
        public string CongViecChiTieu { get; set; }
        public Nullable<System.DateTime> ThucHien { get; set; }
        public Nullable<int> ChiPhiCongViec { get; set; }
    }
}
