//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongViecNhanVien
    {
        public string MaCongViecNhanVien { get; set; }
        public string MaNhanVienPhuTrach { get; set; }
        public string TenCongViec { get; set; }
        public string MoTa { get; set; }
        public string TaiLieu { get; set; }
        public Nullable<int> LuongCongViec { get; set; }
        public Nullable<System.DateTime> DuKienHoanThanh { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public bool TienDo { get; set; }
        public Nullable<System.DateTime> NgayHoanThanh { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
