//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuAn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyDuAnEntities1 : DbContext
    {
        public QuanLyDuAnEntities1()
            : base("name=QuanLyDuAnEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CongViec> CongViecs { get; set; }
        public virtual DbSet<CongViecNhanVien> CongViecNhanViens { get; set; }
        public virtual DbSet<ChiPhi> ChiPhis { get; set; }
        public virtual DbSet<DuAn> DuAns { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<Nhom> Nhoms { get; set; }
    }
}
