//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuAn
    {
        public string MaDuAn { get; set; }
        public string TenDuAn { get; set; }
        public string MucTieuDuAn { get; set; }
        public Nullable<int> ChiPhiDuAn { get; set; }
        public string CongViecDuAn { get; set; }
        public string NhomPhuTrach { get; set; }
        public Nullable<System.DateTime> DuKienHoanThanh { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public int TienDo { get; set; }
        public Nullable<System.DateTime> NgayHoanThanh { get; set; }
    
        public virtual CongViec CongViec { get; set; }
        public virtual Nhom Nhom { get; set; }
        public override string ToString()
        {
            return this.TenDuAn;
        }
    }
}
